
var myHeaders = new Headers();
	myHeaders.append('Content-Type','application/json');
var data2 = {
    id: 2,
    status: true
};
var myInit2 = {method:"POST",headers: myHeaders,body: JSON.stringify(data2), mode: 'cors',cache: 'default'};
var request1 = new Request("http://botnet.artificial.engineering:80/api/Status",myInit2);

fetch(request1).then((response) => {
    return response.json();
}).then((json) => {
    console.log(json);
});

/* When the user clicks on the button, 
toggle between hiding and showing the dropdown content */
var x = document.createElement("SELECT");

var option = document.createElement("option");
var option1 = document.createElement("option");
var option2 = document.createElement("option");
var option3 = document.createElement("option");

option.text = "-";
option1.text = "hash-md5";
option2.text = "hash-sha256";
option3.text = "crack-md5";

x.add(option);
x.add(option1);
x.add(option2);
x.add(option3);

var body = document.querySelector("body");
body.appendChild(x);

x.onchange = function(){changeOpt(x)};
var opt = "";
function changeOpt(x){
       opt = getSelectedOption(x);      
}
function getSelectedOption(x) {
    var opt;
    for ( var i = 0, len = x.options.length; i < len; i++ ) {
        opt = x.options[i];
        if ( opt.selected === true ) {
            break;
        }
    }
    return opt.text;
}
var getText = "";
var text = document.createElement("INPUT");
text.setAttribute("type", "text");
body.appendChild(text);
text.onchange = function() {change()};
function change() { getText = text.value 
return getText;
};
function sendForm(x){
   var data = {
    type: getSelectedOption(x),
    	data: {
        input: change()  // output is generated by Bots
	}
    	
	};
   postRequestTasks(data);
    

}
function postRequestTasks(data){
	var myHeaders = new Headers();
	myHeaders.append('Content-Type','application/json');
	var myInit = {method:"POST",headers: myHeaders,body: JSON.stringify(data), mode: 'cors',cache: 'default'};
	var request = new Request("http://botnet.artificial.engineering:80/api/Tasks/" ,myInit);
	fetch(request).then((response) => {
    		return response.json();
		}).then((json) => {
    		console.log(json);
	});

}


	









