function setInputField() {
  var section = document.getElementsByClassName("active");
  var main = document.querySelector("main");
  console.log(main.childNodes);
  console.log(main.childNodes.length);
  
  if(section[1].id == "tasks-table" && main.childNodes.length == 7) {
    console.log("hurra");
    var myHeaders = new Headers();
	    myHeaders.append('Content-Type','application/json');
    var data2 = {
        id: 2,
        status: true
    };
    var myInit2 = {method:"POST",headers: myHeaders,body: JSON.stringify(data2), mode: 'cors',cache: 'default'};
    var request1 = new Request("http://botnet.artificial.engineering:80/api/Status",myInit2);

    fetch(request1).then((response) => {
        return response.json();
    }).then((json) => {
        console.log(json);
    });

    /* When the user clicks on the button, 
    toggle between hiding and showing the dropdown content */
    var select = document.createElement("SELECT");

    var option = document.createElement("option");
    var option1 = document.createElement("option");
    var option2 = document.createElement("option");
    var option3 = document.createElement("option");

    option.text = "-";
    option1.text = "hash-md5";
    option2.text = "hash-sha256";
    option3.text = "crack-md5";

    select.add(option);
    select.add(option1);
    select.add(option2);
    select.add(option3);

    var main = document.querySelector("main");
    main.appendChild(select);

    select.onchange = function(){changeOpt(select)};
    var opt = "";

    function changeOpt(x){
      opt = getSelectedOption(x);      
    }

    
    var getText = "";
    var text = document.createElement("INPUT");
    text.setAttribute("type", "text");
    main.appendChild(text);

    text.onchange = function() {change()};
    function change() { 
      getText = text.value 
      return getText;
    };

    var button = document.createElement("BUTTON");
    button.innerHTML="send";
    button.onclick = function(){sendForm(select)};
    main.appendChild(button);

  } else {
    if (section[1].id != "tasks-table") {
    var main = document.querySelector("main");
    console.log(main.childNodes);
    console.log(main.childNodes.length);
    main.removeChild(main.childNodes[9]);
    main.removeChild(main.childNodes[8]);
    main.removeChild(main.childNodes[7]);
    //for(var i = main.childNodes.length - 1; i >= main.childNodes.length - 3; i--){
    //main.removeChild(main.childNodes[i]);
    //};
  }
}
};

function getSelectedOption(x) {
      var opt;
      for ( var i = 0, len = x.options.length; i < len; i++ ) {
          opt = x.options[i];
          if ( opt.selected === true ) {
              break;
          }
      }
      return opt.text;
    }


    function sendForm(x){
       var data = {
        type: getSelectedOption(x),
    	    data: {
            input: change()  // output is generated by Bots
        }
    };
    postRequestTasks(data);
    }

    function postRequestTasks(data){
	    var myHeaders = new Headers();
	myHeaders.append('Content-Type','application/json');
	var myInit = {method:"POST",headers: myHeaders,body: JSON.stringify(data), mode: 'cors',cache: 'default'};
	var request = new Request("http://botnet.artificial.engineering:80/api/Tasks/" ,myInit);
	fetch(request).then((response) => {
    		return response.json();
		}).then((json) => {
    		
                 composeTable(tasksServer, taskTableContainer);
	});

    }
